package voluntier.util.eventdata;

public enum Category {
	
	CUIDAR_DE_ANIMAIS,
	ENSINAR_IDIOMAS,
	ENSINAR_MUSICA,
	INICIATIVAS_AMBIENTAIS,
	DESASTRES_AMBIENTAIS,
	COMUNICACAO_DIGITAL,
	AUXILIO_DE_DOENTES,
	AJUDAR_PORTADORES_DE_DEFICIENCIA,
	AJUDA_DESPORTIVA,
	AJUDA_EMPRESARIAL,
	AJUDA_A_CRIANCAS,
	AJUDA_A_IDOSOS,
	AJUDA_A_SEM_ABRIGO,
	PROMOCAO,
	INTERNACIONAL,
	PROTECAO_CIVIL,
	SOCIAL,
	RECICLAGEM,
	CONSTRUCAO
	
}
